import './globals.css'
import type { Metadata } from 'next'
import { ThemeProvider } from '../components/providers/theme-provider'
import { SidebarProvider } from '../components/ui/sidebar'
import { cookies } from 'next/headers'
import { ClerkProvider } from '@clerk/nextjs'
import QueryProvider from '../components/providers/query-provider'
import { Toaster } from '../components/ui/sonner'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const sidebarOpen = cookieStore.get('sidebar_state')?.value === 'true'

  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <body className={` antialiased`}>
        <ClerkProvider>
          <QueryProvider>
            <SidebarProvider defaultOpen={sidebarOpen}>
              <ThemeProvider
                attribute='class'
                enableSystem
                enableColorScheme
                disableTransitionOnChange
                defaultTheme='system'
              >
                {children}
                <Toaster />
              </ThemeProvider>
            </SidebarProvider>
          </QueryProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
